### PR TITLE
Upgrade Nextra 2

### PR DESCRIPTION
**Pull request by zakiego**
Ref https://github.com/shuding/cobe/tree/main/website

### CODE REVIEW

**Comment by zakiego** [comment]
Wait, i'll check where's the sidebar

**Comment by zakiego** [comment]
I think this is enough for me

**Review by kdy1 — APPROVED** [review]
Cool, thank you!

**Comment by zakiego** [comment]
With my pleasure

**Comment by ejcho623** [comment]
is there a way to remove (or update) the github icon without upgrading to v2? it seems like v2 is still not quite ready

it would be great to have an option to remove (or update) the default github icon

**Pull request merged**
